export function prettyMediaLabel(input: {
  url: string;
  fallback?: string;
  kind?: "space" | "experience" | "hero" | "generic";
}): string {
  const { url, fallback, kind = "generic" } = input;

  const file = safeDecode(url.split("/").pop() || "");
  const raw = file.replace(/\.(webp|png|jpg|jpeg)$/i, "");
  const cleaned = humanizeTokens(raw);

  // If filename looks like camera output, use parent folder hint.
  const parent = safeDecode(url.split("/").slice(-2, -1)[0] || "");
  const parentClean = humanizeTokens(parent);

  if (looksAutoGenerated(cleaned)) {
    const fromParent = parentClean && !looksAutoGenerated(parentClean) ? parentClean : "";
    if (fromParent) return refine(fromParent, kind);
    return refine(fallback || (kind === "space" ? "Space" : kind === "experience" ? "Experience" : "View"), kind);
  }

  return refine(cleaned, kind);
}

function refine(label: string, kind: string) {
  const s = label.trim();
  if (!s) return kind === "space" ? "Space" : kind === "experience" ? "Experience" : "View";

  // Small domain-specific polish
  const lower = s.toLowerCase();
  const replacements: Array<[RegExp, string]> = [
    [/bbq/gi, "BBQ"],
    [/tv/gi, "TV"],
    [/ac/gi, "AC"],
    [/dj/gi, "DJ"],
    [/sit ?out/gi, "Sitout"],
    [/out ?door/gi, "Outdoor"],
    [/in ?door/gi, "Indoor"],
    [/court ?yard/gi, "Courtyard"],
    [/walk ?on ?the ?water/gi, "Walk on the Water"],
  ];
  for (const [re, v] of replacements) {
    if (re.test(lower)) return titleCase(s.replace(re, v));
  }
  return titleCase(s);
}

function safeDecode(s: string) {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

function humanizeTokens(s: string) {
  return s
    .replace(/[_]+/g, " ")
    .replace(/[-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function looksAutoGenerated(s: string) {
  const v = s.toLowerCase();
  if (!v) return true;
  // camera-like patterns
  if (/^(img|dji|dsc)\s*\d+/i.test(v)) return true;
  // generic "spaces 12", "hero 2", "xhero"
  if (/^(spaces|space|hero|xhero)\s*\d*$/i.test(v)) return true;
  // mostly digits
  const letters = (v.match(/[a-z]/g) || []).length;
  const digits = (v.match(/[0-9]/g) || []).length;
  if (digits > 0 && letters === 0) return true;
  if (digits >= 6 && letters <= 3) return true;
  return false;
}

function titleCase(s: string) {
  return s
    .split(" ")
    .filter(Boolean)
    .map((w) => (w.length <= 2 ? w.toUpperCase() : w[0].toUpperCase() + w.slice(1)))
    .join(" ");
}

