/**
 * Dashboard CSS class names — pair with `src/styles/dashboard.css`.
 * Components use these instead of inline styles / nested public glass chrome.
 */

export const dash = {
  root: "dashboard-root",
  shell: "dashboard-shell",
  main: "dashboard-main",
  content: "dashboard-content",
  page: "dashboard-page",

  panel: "dashboard-panel",
  panelBody: "dashboard-panel__body",
  panelPad: "dashboard-panel dashboard-panel--pad",
  panelFill: "dashboard-panel dashboard-panel--fill",
  panelFillPad: "dashboard-panel dashboard-panel--pad dashboard-panel--fill",
  panelHeader: "dashboard-panel__header",

  header: "dashboard-header",
  headerInner: "dashboard-header__inner",
  headerBrand: "dashboard-header__brand",
  headerLogo: "dashboard-header__logo",
  headerTitleBlock: "dashboard-header__title-block",
  headerSection: "dashboard-header__section",
  headerTitle: "dashboard-header__title",
  headerDesc: "dashboard-header__desc",
  headerActions: "dashboard-header__actions",
  headerAssist: "dashboard-header__assist",
  headerAssistLabel: "dashboard-header__assist-label",

  sidebarMobile: "dashboard-sidebar dashboard-sidebar--mobile",
  sidebarMobileOpen: "dashboard-sidebar dashboard-sidebar--mobile dashboard-sidebar--open",
  sidebarDesktop: "dashboard-sidebar dashboard-sidebar--desktop",
  sidebarFrame: "dashboard-sidebar__frame",
  sidebarGlassFill: "dashboard-glass__fill",
  sidebarBrand: "dashboard-sidebar__brand",
  sidebarBrandRow: "dashboard-sidebar__brand-row",
  sidebarLogo: "dashboard-sidebar__logo",
  sidebarNav: "dashboard-sidebar__nav",
  sidebarSection: "dashboard-sidebar__section",
  sidebarSectionLabel: "dashboard-sidebar__section-label",
  sidebarLink: "dashboard-sidebar__link",
  sidebarLinkActive: "dashboard-sidebar__link dashboard-sidebar__link--active",
  sidebarLinkIcon: "dashboard-sidebar__link-icon",
  sidebarLinkLabel: "dashboard-sidebar__link-label",
  sidebarLinkActiveBar: "dashboard-sidebar__link-active-bar",
  sidebarFooter: "dashboard-sidebar__footer",
  sidebarUserCard: "dashboard-sidebar__user-card",
  sidebarViewSite: "dashboard-sidebar__view-site",
  overlay: "dashboard-overlay",
  overlayVisible: "dashboard-overlay dashboard-overlay--visible",

  btn: "dashboard-btn",
  btnIcon: "dashboard-btn dashboard-btn--icon",
  btnText: "dashboard-btn dashboard-btn--text",
  btnAccent: "dashboard-btn dashboard-btn--accent",
  btnDense: "dashboard-btn dashboard-btn--dense",
  btnCompact: "dashboard-btn dashboard-btn--icon dashboard-btn--compact",

  btnGhost: "dashboard-btn dashboard-btn--icon dashboard-btn--ghost",

  inputWrap: "dashboard-input-wrap",
  inputIcon: "dashboard-input-wrap__icon",
  inputIconLeft: "dashboard-input dashboard-input--icon-left",
  input: "dashboard-input",
  inputCompact: "dashboard-input dashboard-input--compact",
  intro: "dashboard-intro",
  chip: "dashboard-chip",
  label: "dashboard-label",
  muted: "dashboard-muted",

  stats: "dashboard-stats",
  statsItem: "dashboard-stats__item",
  statRow: "dashboard-stat__row",
  statIcon: "dashboard-stat__icon",
  statLabel: "dashboard-stat__label",
  statValue: "dashboard-stat__value",

  toolbar: "dashboard-toolbar",
  toolbarMeta: "dashboard-toolbar__meta",
  toolbarActions: "dashboard-toolbar__actions",
  toolbarActionsList: "dashboard-toolbar__actions dashboard-toolbar__actions--list",
  toolbarSegment: "dashboard-toolbar__segment",
  toolbarSearch: "dashboard-toolbar__search",
  toolbarNav: "dashboard-toolbar__nav",
  toolbarDaysSelect: "dashboard-toolbar__days-select",
  toolbarTodayBtn: "dashboard-toolbar__today-btn",
  toolbarFilters: "dashboard-toolbar__filters",

  scrollRow: "dashboard-scroll-row",
  user: "dashboard-user",
  userAvatar: "dashboard-user__avatar",
  userName: "dashboard-user__name",
  userRole: "dashboard-user__role",

  tableWrap: "dashboard-table-wrap",
  dataTableWrap: "dashboard-data-table-wrap dashboard-data-table-wrap--menus",
  dataTable: "dashboard-data-table",
  dataTableScrollHint: "dashboard-data-table-scroll-hint",
  dataTableEmpty: "dashboard-data-table__empty",
  emptyState: "dashboard-empty-state",
  emptyStateIcon: "dashboard-empty-state__icon",
  emptyStateTitle: "dashboard-empty-state__title",
  emptyStateDesc: "dashboard-empty-state__desc",
  errorText: "dashboard-error-text",
  successText: "dashboard-success-text",
  loadingRow: "dashboard-loading-row",
  calScrollHint: "dashboard-cal-scroll-hint",
  calTable: "dashboard-cal-table",
  calVilla: "dashboard-cal-villa",
  calVillaHead: "dashboard-cal-villa dashboard-cal-villa--head",
  calVillaName: "dashboard-cal-villa__name",
  calVillaMeta: "dashboard-cal-villa__meta",
  calDay: "dashboard-cal-day",
  calDayToday: "dashboard-cal-day dashboard-cal-day--today",
  calDayWeekend: "dashboard-cal-day dashboard-cal-day--weekend",
  calDaySub: "dashboard-cal-day__sub",
  calOccLabel: "dashboard-cal-occ-label",
  calOccBar: "dashboard-cal-occ-bar",
  calCell: "dashboard-cal-cell",
  calCellToday: "dashboard-cal-cell dashboard-cal-cell--today",
  calCellWeekend: "dashboard-cal-cell dashboard-cal-cell--weekend",
  calCellEmpty: "dashboard-cal-cell__empty",
  calCellOffline: "dashboard-cal-cell__offline",
  calCellBlock: "dashboard-cal-cell__block",
  calBooking: "dashboard-cal-booking",
  legend: "dashboard-legend",
  legendItem: "dashboard-legend__item",

  onlyMobile: "dashboard-only-mobile",
  onlyDesktop: "dashboard-only-desktop",
  hiddenLg: "dashboard-hidden-lg",
  smHidden: "dashboard-sm-hidden",
  lgOnly: "dashboard-lg-only",

  modalOverlay: "dashboard-modal-overlay",
  modal: "dashboard-modal",
  modalWide: "dashboard-modal dashboard-modal--wide",
  modalBody: "dashboard-modal__body",
  stack: "dashboard-stack",
  formGrid: "dashboard-form-grid",
  formGrid2: "dashboard-form-grid dashboard-form-grid--2",
  fieldError: "dashboard-field-error",
  logDetail: "dashboard-log-detail",

  module: "dash-module",
  moduleBody: "dash-module__body",
  tabBar: "dash-tab-bar",
  filterBar: "dash-filter-bar",
  filterSearch: "dash-filter-bar__search",
  filterSearchIcon: "dash-filter-bar__search-icon",
  filterSelect: "dash-filter-bar__select",
  filterActions: "dash-filter-bar__actions",
  kpiStrip: "dash-kpi-strip",
  badge: "dash-badge",
  dropdownMenu: "dash-dropdown-menu",
} as const;

/** Accent color classes for stat icons */
export const dashAccent = {
  gold: "text-[var(--dash-accent)]",
  sky: "text-[var(--dash-info)]",
  amber: "text-[var(--dash-warning)]",
  red: "text-[var(--dash-danger)]",
} as const;
